const people = [
  {
    surname: "Smith",
    firstname: "John",
    role: "Staff",
    position: "Manager",
    bloodGroup: "A",
    genotype: "AA",
    dateOfBirth: "1990-05-15",
    email: "john.smith@example.com",
    password: "hashed_staff_password_1",
  },
  {
    surname: "Johnson",
    firstname: "Jane",
    role: "Staff",
    position: "Assistant",
    bloodGroup: "B",
    genotype: "BB",
    dateOfBirth: "1988-07-20",
    email: "jane.johnson@example.com",
    password: "hashed_staff_password_2",
  },
  {
    surname: "Doe",
    firstname: "Alice",
    role: "Staff",
    position: "Supervisor",
    bloodGroup: "O",
    genotype: "OO",
    dateOfBirth: "1983-03-10",
    email: "alice.doe@example.com",
    password: "hashed_staff_password_3",
  },
  {
    surname: "Williams",
    firstname: "Robert",
    role: "Staff",
    position: "Coordinator",
    bloodGroup: "A",
    genotype: "AA",
    dateOfBirth: "1986-12-05",
    email: "robert.williams@example.com",
    password: "hashed_staff_password_4",
  },
  {
    surname: "Taylor",
    firstname: "Emily",
    role: "Staff",
    position: "Specialist",
    bloodGroup: "AB",
    genotype: "AB",
    dateOfBirth: "1992-09-25",
    email: "emily.taylor@example.com",
    password: "hashed_staff_password_5",
  },
  {
    surname: "Jones",
    firstname: "David",
    role: "Staff",
    position: "Analyst",
    bloodGroup: "B",
    genotype: "BB",
    dateOfBirth: "1989-06-18",
    email: "david.jones@example.com",
    password: "hashed_staff_password_6",
  },
  {
    surname: "Brown",
    firstname: "Emma",
    role: "Staff",
    position: "Developer",
    bloodGroup: "O",
    genotype: "OO",
    dateOfBirth: "1991-04-12",
    email: "emma.brown@example.com",
    password: "hashed_staff_password_7",
  },
  {
    surname: "Miller",
    firstname: "Michael",
    role: "Staff",
    position: "Designer",
    bloodGroup: "A",
    genotype: "AA",
    dateOfBirth: "1984-08-30",
    email: "michael.miller@example.com",
    password: "hashed_staff_password_8",
  },
  {
    surname: "Anderson",
    firstname: "Olivia",
    role: "Staff",
    position: "Engineer",
    bloodGroup: "B",
    genotype: "BB",
    dateOfBirth: "1993-11-08",
    email: "olivia.anderson@example.com",
    password: "hashed_staff_password_9",
  },
  {
    surname: "Davis",
    firstname: "Daniel",
    role: "Staff",
    position: "Coordinator",
    bloodGroup: "O",
    genotype: "OO",
    dateOfBirth: "1987-02-22",
    email: "daniel.davis@example.com",
    password: "hashed_staff_password_10",
  },
];
export default people