let patientdata = [
  {
    surname: "Doe",
    firstname: "John",
    gender: "Male",
    age: "30",
    bloodGroup: "O+",
    genotype: "AA",
    dateOfBirth: "1992-05-15",
    contactNumber: 1234567890,
    email: "john.doe@example.com",
    password: "hashed_password_1",
  },
  {
    surname: "Smith",
    firstname: "Jane",
    gender: "Female",
    age: "25",
    bloodGroup: "A-",
    genotype: "AS",
    dateOfBirth: "1997-09-22",
    contactNumber: 9876543210,
    email: "jane.smith@example.com",
    password: "hashed_password_2",
  },
  {
    surname: "Johnson",
    firstname: "Robert",
    gender: "Male",
    age: "45",
    bloodGroup: "B+",
    genotype: "AA",
    dateOfBirth: "1978-12-10",
    contactNumber: 5678901234,
    email: "robert.johnson@example.com",
    password: "hashed_password_3",
  },
  {
    surname: "Williams",
    firstname: "Emily",
    gender: "Female",
    age: "28",
    bloodGroup: "AB-",
    genotype: "AS",
    dateOfBirth: "1994-03-18",
    contactNumber: 6789012345,
    email: "emily.williams@example.com",
    password: "hashed_password_4",
  },
  {
    surname: "Brown",
    firstname: "Christopher",
    gender: "Male",
    age: "32",
    bloodGroup: "O-",
    genotype: "AO",
    dateOfBirth: "1989-08-05",
    contactNumber: 7890123456,
    email: "christopher.brown@example.com",
    password: "hashed_password_5",
  },
  {
    surname: "Davis",
    firstname: "Olivia",
    gender: "Female",
    age: "22",
    bloodGroup: "A+",
    genotype: "AA",
    dateOfBirth: "2001-02-28",
    contactNumber: 8901234567,
    email: "olivia.davis@example.com",
    password: "hashed_password_6",
  },
  {
    surname: "Martinez",
    firstname: "Daniel",
    gender: "Male",
    age: "40",
    bloodGroup: "B-",
    genotype: "AS",
    dateOfBirth: "1983-11-15",
    contactNumber: 9012345678,
    email: "daniel.martinez@example.com",
    password: "hashed_password_7",
  },
  {
    surname: "Garcia",
    firstname: "Sophia",
    gender: "Female",
    age: "26",
    bloodGroup: "AB+",
    genotype: "AA",
    dateOfBirth: "1996-07-09",
    contactNumber: 1234567890,
    email: "sophia.garcia@example.com",
    password: "hashed_password_8",
  },
  {
    surname: "Rodriguez",
    firstname: "Michael",
    gender: "Male",
    age: "36",
    bloodGroup: "O+",
    genotype: "AO",
    dateOfBirth: "1987-04-23",
    contactNumber: 2345678901,
    email: "michael.rodriguez@example.com",
    password: "hashed_password_9",
  },
  {
    surname: "Martinez",
    firstname: "Emma",
    gender: "Female",
    age: "29",
    bloodGroup: "B+",
    genotype: "AS",
    dateOfBirth: "1993-09-30",
    contactNumber: 3456789012,
    email: "emma.martinez@example.com",
    password: "hashed_password_10",
  },
  {
    surname: "Taylor",
    firstname: "Alexander",
    gender: "Male",
    age: "33",
    bloodGroup: "AB-",
    genotype: "AO",
    dateOfBirth: "1988-06-14",
    contactNumber: 4567890123,
    email: "alexander.taylor@example.com",
    password: "hashed_password_11",
  },
  {
    surname: "Hernandez",
    firstname: "Ava",
    gender: "Female",
    age: "23",
    bloodGroup: "A+",
    genotype: "AS",
    dateOfBirth: "2000-01-05",
    contactNumber: 5678901234,
    email: "ava.hernandez@example.com",
    password: "hashed_password_12",
  },
  {
    surname: "Garcia",
    firstname: "William",
    gender: "Male",
    age: "41",
    bloodGroup: "O-",
    genotype: "AA",
    dateOfBirth: "1982-08-20",
    contactNumber: 6789012345,
    email: "william.garcia@example.com",
    password: "hashed_password_13",
  },
];
export default patientdata